# Generated by Django 2.2.17 on 2020-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201205_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=250)),
                ('taste', models.CharField(max_length=250)),
                ('impressions', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
