# Generated by Django 2.2.17 on 2021-01-11 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coffull_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='uuid',
            field=models.UUIDField(default=None, editable=True, null=True, serialize=False),
            preserve_default=False,        ),
    ]
