# Generated by Django 2.2.17 on 2021-01-11 03:06

from django.db import migrations, models
import uuid
 
def gen_uuid(apps, schema_editor):
    Coffee = apps.get_model('coffull_api', 'Coffee')
    for row in Coffee.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('coffull_api', '0002_auto_20210111_0333'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='Coffee',
            name='id',
        ),
        migrations.AlterField(
            model_name='Coffee',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
