# Generated by Django 2.2.17 on 2021-01-11 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coffull_api', '0003_auto_20210111_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=250)),
                ('taste', models.CharField(max_length=250)),
                ('impressions', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
