# Generated by Django 2.2.17 on 2021-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffull_api', '0005_auto_20210112_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeenote',
            name='feature',
            field=models.CharField(db_column='feature', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coffeenote',
            name='impression',
            field=models.CharField(db_column='impression', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coffeenote',
            name='taste',
            field=models.CharField(db_column='taste', max_length=250, null=True),
        ),
    ]
